name: Trading Bot 15m
on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install Libraries
        run: pip install ccxt pandas ta
      - name: Run Bot
        env:
          MEXC_API_KEY: ${{ secrets.MEXC_API_KEY }}
          MEXC_SECRET_KEY: ${{ secrets.MEXC_SECRET_KEY }}
        run: python bot.py
